nelmio_api_doc:
    documentation:
        info:
            title: Payment Date Tracker
            description: The Sales Payroll Generator is a tool designed to help a fictional company automate the process of calculating and tracking payment dates for their sales staff.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
