name: CI/CD

on:
  push:
    branches:
      - 'main'
      - 'release'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    if: ${{ ! startsWith(github.event.head_commit.message, 'chore(release)') }}
    uses: ./.github/workflows/docker_build.yml
    concurrency:
      group: ${{ github.ref }}-build
      cancel-in-progress: true
    with:
      username: ${{ github.actor }}
      image: ${{ github.repository }}
      registry: ghcr.io
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  static_analysis:
    if: ${{ ! startsWith(github.event.head_commit.message, 'chore(release)') }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-static_analysis
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: output - cache-files-dir
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: run - composer install
        run: composer install --prefer-dist --no-scripts

      - name: run - psalm
        env:
          APP_ENV: test
        run: vendor/bin/psalm --threads=8 --stats --output-format=github